id: A2BB0BC31
base_file: f22EB.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:27:43.589231
  last_modified_at: 2022-05-30 18:27:43.589237
