id: A2BB0BC31
base_file: f7DD5.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:27:43.592352
  last_modified_at: 2022-05-30 18:27:43.592356
