id: A2BB0BC31
base_file: fCD4A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:27:43.595269
  last_modified_at: 2022-05-30 18:27:43.595273
